version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: production
    ports:
      - "3400:3400"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:3000/api
    restart: always
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/linkedin_generator
    restart: always
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: linkedin_generator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
